ALTER TABLE clients      ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE insurances   ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE documents    ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE payments     ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE appointments ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE templates    ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE users        ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
